### ISSUE TITLE
模块报错：安装后odoo很多东西都打不开！

### ISSUE THREAD

**Issue by leangjia** [jellyfrank/china_city#1]
OS：ubuntu14.04server+odoo8.0-20160831+postgresql9.3
未安装此模块前odoo正常使用中，上传模块至odoo的addos目录下之后odoo无法打开。

**Comment by leangjia** [comment]
@kevin8909

**Comment by leangjia** [comment]
请知悉！

**Comment by jellyfrank** [comment]
卧槽，我这才看见。。。

**Comment by jellyfrank** [comment]
新模块已经转移到o[os](https://github.com/block-cat/os)中
